### ISSUE TITLE
leverage executemany to stream data

### ISSUE THREAD

**Issue by braunreyes** [PrefectHQ/prefect-snowflake#41]
In using the current main branch version of the library and leveraging the basic example of creating a credentials and connection object, when the query execution is running a long running query and the flow run gets canceled via  
Command + C, the snowflake query is not getting canceled.

```
snowflake_credentials = SnowflakeCredentials(
        account="account",
        user="login",
        autocommit=True,
        password=os.getenv("PRIVATE_KEY_PASSPHRASE"),
        private_key="private key string",
        role="sysadmin",
    )
    snowflake_connector = SnowflakeConnector(
        database="development",
        warehouse="compute_wh",
        schema="braun",
        credentials=snowflake_credentials,
    )
    file_counter = 0
    with snowflake_connector.get_connection() as sf:
        with sf.cursor() as cur:
            cur.execute("long running query")
```

I would expect this to behave the same way as using the snowflake connector directly.

**Comment by ahuang11** [comment]
Curious if you have a traceback?

Also, what if you tried using the built-in [snowflake_query](https://github.com/PrefectHQ/prefect-snowflake/blob/main/prefect_snowflake/database.py#L120)?

**Comment by braunreyes** [comment]
So here is the stack trace on running keyboard interrupt twice, which you have to do because the first one hangs:

```
12:47:28.716 | INFO    | prefect.engine - Created flow run 'great-buffalo' for flow 'snowflake-query-flow'
^C12:49:17.709 | ERROR   | Flow run 'great-buffalo' - Crash detected! Execution was cancelled by the runtime environment.
Traceback (most recent call last):
  File "/Users/mozilla/projects/dpt-data-flows/src/flows/article_testing.py", line 77, in <module>
    snowflake_query_flow()
  File "/Users/mozilla/projects/dpt-data-flows/.venv/lib/python3.10/site-packages/prefect/flows.py", line 447, in __call__
    return enter_flow_run_engine_from_flow_call(
  File "/Users/mozilla/projects/dpt-data-flows/.venv/lib/python3.10/site-packages/prefect/engine.py", line 162, in enter_flow_run_engine_from_flow_call
    return anyio.run(begin_run)
  File "/Users/mozilla/projects/dpt-data-flows/.venv/lib/python3.10/site-packages/anyio/_core/_eventloop.py", line 70, in run
    return asynclib.run(func, *args, **backend_options)
  File "/Users/mozilla/projects/dpt-data-flows/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 292, in run
    return native_run(wrapper(), debug=debug)
  File "/Users/mozilla/.pyenv/versions/3.10.7/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/mozilla/.pyenv/versions/3.10.7/lib/python3.10/asyncio/base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "/Users/mozilla/.pyenv/versions/3.10.7/lib/python3.10/asyncio/base_events.py", line 600, in run_forever
    self._run_once()
  File "/Users/mozilla/.pyenv/versions/3.10.7/lib/python3.10/asyncio/base_events.py", line 1860, in _run_once
    event_list = self._selector.select(timeout)
  File "/Users/mozilla/.pyenv/versions/3.10.7/lib/python3.10/selectors.py", line 562, in select
    kev_list = self._selector.control(None, max_ev, timeout)
KeyboardInterrupt
^CException ignored in: <module 'threading' from '/Users/mozilla/.pyenv/versions/3.10.7/lib/python3.10/threading.py'>
Traceback (most recent call last):
  File "/Users/mozilla/.pyenv/versions/3.10.7/lib/python3.10/threading.py", line 1567, in _shutdown
    lock.acquire()
KeyboardInterrupt: 
```

The query I am running is much more complex than my example.  I needed to leverage executemany to stream data into files, which is why I opted to use native functions for snowflake connector.

```
with snowflake_connector.get_connection() as sf:
        with sf.cursor() as cur:
            results = cur.execute(sql)
            batch = results.fetchmany(10000)
            while len(batch) > 0:
                batch_filter = ",".join([f"{x[0]}" for x in batch])
                with open(f"/tmp/file_{file_counter}", "w") as f:
                    with sf.cursor() as cur_inner:
                        text = cur_inner.execute(
                            f"""select resolved_id, text 
        from raw.item.article_content_v2
        where resolved_id in ({batch_filter})"""
                        )
                        for col1, col2 in text:
                            f.write(f"{col1}    {col2}")
                file_counter += 1
                batch = results.fetchmany(10000)
```

**Comment by braunreyes** [comment]
I guess it would good to know how someone should leverage native commands and leverage fetchmany and connection.multi_statement as find them to be super helpful.  The best part of this library I think are the connection and credentials abstractions.  Even being able to use the snowflake pandas stuff like in the readme.  I would think maybe canceling that would a similar behavior.

**Comment by ahuang11** [comment]
To clarify to make sure I understand, you were able to KeyboardInterrupt the query (but had to do it twice)?

Also, does [`snowflake_multiquery`](https://github.com/PrefectHQ/prefect-snowflake/blob/main/prefect_snowflake/database.py#L187) task support your use case, then use a `LIMIT 1000` statement to fetchmany?
