### ISSUE TITLE
Receiving AttributeError: __enter__ when running prefect-snowflake example code

### ISSUE THREAD

**Issue by ab41996** [PrefectHQ/prefect-snowflake#75]
# Expectation / Proposal
When running the following code in prefect-snowflake examples I receive the below error

```python
from prefect import flow, task
from prefect_snowflake import SnowflakeConnector


@task
def setup_table(block_name: str) -> None:
    with SnowflakeConnector.load(block_name) as connector:
        connector.execute(
            "CREATE TABLE IF NOT EXISTS customers (name varchar, address varchar);"
        )
        connector.execute_many(
            "INSERT INTO customers (name, address) VALUES (%(name)s, %(address)s);",
            seq_of_parameters=[
                {"name": "Ford", "address": "Highway 42"},
                {"name": "Unknown", "address": "Space"},
                {"name": "Me", "address": "Myway 88"},
            ],
        )

@task
def fetch_data(block_name: str) -> list:
    all_rows = []
    with SnowflakeConnector.load(block_name) as connector:
        while True:
            # Repeated fetch* calls using the same operation will
            # skip re-executing and instead return the next set of results
            new_rows = connector.fetch_many("SELECT * FROM customers", size=2)
            if len(new_rows) == 0:
                break
            all_rows.append(new_rows)
    return all_rows

@flow
def snowflake_flow(block_name: str) -> list:
    setup_table(block_name)
    all_rows = fetch_data(block_name)
    return all_rows

snowflake_flow()
```

# Traceback / Example
```
Encountered exception during execution:
Traceback (most recent call last):
  File "/Users/anandbhakta/python/data-warehouse/Prefect/.venv/lib/python3.10/site-packages/prefect/engine.py", line 1247, in orchestrate_task_run
    result = await run_sync(task.fn, *args, **kwargs)
  File "/Users/anandbhakta/python/data-warehouse/Prefect/.venv/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 68, in run_sync_in_worker_thread
    return await anyio.to_thread.run_sync(call, cancellable=True)
  File "/Users/anandbhakta/python/data-warehouse/Prefect/.venv/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/Users/anandbhakta/python/data-warehouse/Prefect/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/Users/anandbhakta/python/data-warehouse/Prefect/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/Users/anandbhakta/python/data-warehouse/Prefect/viator_weekly.py", line 72, in setup_table
    with SnowflakeConnector.load(block_name) as connector:
AttributeError: __enter__
```

- [ ] I would like to [help contribute](https://PrefectHQ.github.io/prefect-snowflake/#contributing) a pull request to resolve this!

**Comment by desertaxle** [comment]
Thanks for opening this issue @ab41996! Can you confirm that you created a Snowflake Connector block prior to running this code and that you passed the name of the block into `snowflake_flow` when running this example?

**Comment by ab41996** [comment]
Hi yes can confirm I used a block which I had named "personal-snowflake-conn" with credentials from my credential block "personal-snowflake"

**Comment by ahuang11** [comment]
Hi @ab41996, can you share `prefect version` and `pip show prefect-snowflake`? I suspect you're using an older version of prefect-snowflake.

Mine is:
```
Version:             2.7.7
API version:         0.8.4

Name: prefect-snowflake
Version: 0.26.1
```


I was able to run this successfully:
![image](https://user-images.githubusercontent.com/15331990/220717413-3e64d352-7476-4917-9111-0ffca2ac29b9.png)


```
from prefect import flow, task
from prefect_snowflake import SnowflakeConnector


@task
def setup_table(block_name: str) -> None:
    with SnowflakeConnector.load(block_name) as connector:
        connector.execute(
            "CREATE TABLE IF NOT EXISTS customers2 (name varchar, address varchar);"
        )
        connector.execute_many(
            "INSERT INTO customers2 (name, address) VALUES (%(name)s, %(address)s);",
            seq_of_parameters=[
                {"name": "Ford", "address": "Highway 42"},
                {"name": "Unknown", "address": "Space"},
                {"name": "Me", "address": "Myway 88"},
            ],
        )

@task
def fetch_data(block_name: str) -> list:
    all_rows = []
    with SnowflakeConnector.load(block_name) as connector:
        while True:
            # Repeated fetch* calls using the same operation will
            # skip re-executing and instead return the next set of results
            new_rows = connector.fetch_many("SELECT * FROM customers2", size=2)
            if len(new_rows) == 0:
                break
            all_rows.append(new_rows)
    return all_rows

@flow
def snowflake_flow(block_name: str) -> list:
    setup_table(block_name)
    all_rows = fetch_data(block_name)
    return all_rows

snowflake_flow("snowflake-connector")
```

**Comment by ab41996** [comment]
Version:             2.8.2
API version:         0.8.4

Name: prefect-snowflake
Version: 0.2.2

**Comment by ab41996** [comment]
Have updated my prefect-snowflake version and it is now running fine apologies for wasting your time :)
